#include "game.h"
#include "images/pusheen.h"
#include "images/background.h"
#include "images/start.h"
#include "images/cake.h"
#include "images/donut.h"
#include "images/cookie.h"
#include "images/death.h"
#include "images/success.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "logic.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
<<<<<<< HEAD
=======
  WAIT_FOR_INPUT,
  RULES,
  INI,
>>>>>>> 48611eed9f34d5e9acefddbf687f9720dc3c27b6
  PLAY,
  WIN,
  LOSE,
} GBAState;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;
  int blinkCounter = 0;
  // int wipeAnimationCounter = 0;

  // int playerWon = 0;

  // Load initial game state
  GBAState state = START;


  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons
    if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
        state = START;
        initialize();
    }

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    
    switch (state) {
      case START:

        // state = ?
        waitForVBlank();
        drawFullScreenImageDMA(start);
        // drawImageDMA(SCREEN_WIDTH/2,SCREEN_HEIGHT/2,50,50,pusheen);
        state = WAIT_FOR_INPUT;
        break;
      case WAIT_FOR_INPUT:
        blinkCounter++;
        waitForVBlank();
        if (blinkCounter % 50 >= 25)
        {
            drawCenteredString(0, 131, SCREEN_WIDTH, 10, "Press Start", BLACK);
            drawCenteredString(0, 130, SCREEN_WIDTH, 10, "Press Start", YELLOW);
        }
        else
        {
            drawFullScreenImagePortionDMA(0, 130, SCREEN_WIDTH, 10, start);
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
        {
            state = RULES;
        }
        break;
      case RULES:
          waitForVBlank();
          drawFullScreenImageDMA(background);
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
          {
              drawCenteredString(0, 25, SCREEN_WIDTH, 10, "Control Pusheen to get cakes", MAGENTA);
              drawCenteredString(0, 60, SCREEN_WIDTH, 10, "Eat bombs you die", MAGENTA);
              drawCenteredString(0, 70, SCREEN_WIDTH, 10, "Miss 5 cakes you die", MAGENTA);
              drawCenteredString(0, 100, SCREEN_WIDTH, 10, "Move by <- and ->", WHITE);
              delay(100);
              state = INI;
          }
          break;
      case INI:
        waitForVBlank();
        drawRectDMA(0,0,240,240,BLACK);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons))
        {
          drawRectDMA(0,0,240,240,BLACK);
          // drawImageDMA(0,80,30,30,pusheen);
          // drawImageDMA(30,30,20,20,cake);
          initialize();
          state = PLAY;
        }
      case PLAY:
        waitForVBlank();
        movePlayer(currentButtons,previousButtons);
        display();
        // moveFood();
        // state = ?
        if (getScore() < 0) {
          state = LOSE;
        } else if (getScore() > 100) {
          state = WIN;
        }
        break;
      case WIN:
        waitForVBlank();
        drawFullScreenImageDMA(success);
        // state = ?
        break;
      case LOSE:
        waitForVBlank();
        drawFullScreenImageDMA(death);
        // state = ?
        break;
    }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }

  UNUSED(previousButtons);  // You can remove this once previousButtons is used

  return 0;
}